services:
  privacyidea:
    build: ./privacyidea
    container_name: privacyidea
    env_file: ".env"
    ports:
      - "5000:5000"
    networks:
      - pi_net
    volumes:
      - privacyidea_etc:/etc/privacyidea
      - ./privacyidea_logs:/var/log/privacyidea
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 50s
      timeout: 5s
      retries: 3
      start_period: 15s


  freeradius:
    build: ./freeradius
    container_name: freeradius
    depends_on:
      privacyidea:
        condition: service_healthy
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    env_file: ".env"
    networks:
      - pi_net
    volumes:
      - privacyidea_etc:/etc/privacyidea  
    healthcheck:
      test: ["CMD-SHELL", "echo | nc -uzv -w1 localhost 1812 || exit 1"]
      interval: 50s
      timeout: 5s
      retries: 3
      start_period: 15s


volumes:
  privacyidea_etc:
  privacyidea_logs:

networks:
  pi_net:
    driver: bridge
