services:
  db:
    build: ./postgres
    container_name: pi_postgres
    env_file: ".env"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  
    networks:
      - pi_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PI_DB_USER} -d ${PI_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  privacyidea:
    build: ./privacyidea
    container_name: privacyidea
    env_file: ".env"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    networks:
      - pi_net
    volumes:
      - privacyidea_etc:/etc/privacyidea
      - privacyidea_data:/var/lib/privacyidea
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 50s
      timeout: 5s
      retries: 3
      start_period: 5s


  freeradius:
    build: ./freeradius
    container_name: freeradius
    depends_on:
      privacyidea:
        condition: service_healthy
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    env_file: ".env"
    networks:
      - pi_net
    healthcheck:
      test: ["CMD-SHELL", "echo | nc -uzv -w1 localhost 1812 || exit 1"]
      interval: 50s
      timeout: 5s
      retries: 3
      start_period: 5s


volumes:
  pgdata:
  privacyidea_etc:
  privacyidea_data:

networks:
  pi_net:
    driver: bridge
