CREATE USER pi_user WITH PASSWORD 'test123';
CREATE DATABASE pi_db OWNER pi_user;
GRANT ALL PRIVILEGES ON DATABASE pi_db TO pi_user;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    rpcm_group VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
